identifier_name:
    excluded:
        - id
        - ok
        - x
        - y
disabled_rules:
        trailing_comma
custom_rules:
    empty_line_after_guard: # from https://github.com/brandenr/swiftlintconfig
        name: 'Empty Line After Guard'
        regex: '(^ *guard[ a-zA-Z0-9=?.\(\),><!]*\{[ a-zA-Z0-9=?.\(\),><!]*\}\n *(?!(?:return|guard))\S+)'
        message: 'There should be an empty line after a guard'
        severity: warning
